# Generated by Django 6.1 on 2026-08-18 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, default='default_user', help_text='User identifier for isolation and session ownership.', max_length=150)),
                ('memory_type', models.CharField(choices=[('preference', 'Preference'), ('family', 'Family'), ('interest', 'Interest'), ('general', 'General')], db_index=True, default='general', max_length=50)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Memory',
                'verbose_name_plural': 'User Memories',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user_identifier', 'memory_type', 'key'), name='unique_memory_per_user_key')],
            },
        ),
    ]
