# Generated by Django 6.1 on 2026-10-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemory',
            name='memory_type',
            field=models.CharField(choices=[('preference', 'Preference'), ('family', 'Family'), ('interest', 'Interest'), ('lifestyle', 'Lifestyle'), ('general', 'General')], db_index=True, default='general', max_length=50),
        ),
    ]
