# Generated by Django 6.1 on 2026-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_alter_usermemory_memory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, default='default_user', help_text='User identifier — matches the voice request user_identifier.', max_length=150)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=10)),
                ('category', models.CharField(choices=[('NONE', 'None'), ('MEDICATION', 'Medication'), ('FALL', 'Fall'), ('MEDICAL', 'Medical'), ('CONFUSION', 'Confusion'), ('SAFETY', 'Safety'), ('EMOTIONAL_DISTRESS', 'Emotional Distress'), ('SELF_HARM', 'Self Harm'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], db_index=True, default='NONE', max_length=30)),
                ('reason', models.TextField(blank=True, default='', help_text='Short plain-English description of the detected concern.')),
                ('relevant_text', models.CharField(blank=True, default='', help_text='Short excerpt (max 200 chars) of the transcript that triggered the alert.', max_length=200)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved')], db_index=True, default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Safety Event',
                'verbose_name_plural': 'Safety Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
