# Generated by Django 6.1 on 2026-10-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_stage9_safety_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, help_text='User identifier for voice preference ownership.', max_length=150, unique=True)),
                ('provider', models.CharField(choices=[('piper', 'Piper'), ('elevenlabs', 'ElevenLabs')], default='piper', help_text="TTS provider ('piper' or 'elevenlabs').", max_length=20)),
                ('elevenlabs_voice_id', models.CharField(blank=True, default='', help_text='Optional custom ElevenLabs voice ID for personalized voice cloning.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Voice Preference',
                'verbose_name_plural': 'User Voice Preferences',
                'ordering': ['-updated_at'],
            },
        ),
    ]
