# Generated by Django 6.1 on 2026-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_uservoicepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoicepreference',
            name='openvoice_reference_path',
            field=models.CharField(blank=True, default='', help_text='Optional local file path to reference voice audio for OpenVoice V2 cloning.', max_length=500),
        ),
        migrations.AlterField(
            model_name='uservoicepreference',
            name='provider',
            field=models.CharField(choices=[('piper', 'Piper'), ('elevenlabs', 'ElevenLabs'), ('openvoice', 'OpenVoice (Local)')], default='piper', help_text="TTS provider ('piper', 'elevenlabs', or 'openvoice').", max_length=20),
        ),
    ]
