# Generated by Django 6.1 on 2026-10-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0005_uservoicepreference_openvoice_reference_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, help_text='Internal user identifier for this senior (e.g. default_user or session uid).', max_length=150, unique=True)),
                ('senior_id', models.CharField(db_index=True, help_text='Public unique Senior ID (e.g. SM-7K4P-9Q2X).', max_length=30, unique=True)),
                ('display_name', models.CharField(default='Senior Citizen', help_text='Display name chosen by the senior.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Senior Profile',
                'verbose_name_plural': 'Senior Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverElderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker_phone', models.CharField(db_index=True, help_text='Caretaker phone number or contact identifier.', max_length=30)),
                ('caretaker_name', models.CharField(default='Caregiver', help_text='Caretaker name.', max_length=150)),
                ('caretaker_slot', models.CharField(default='PRIMARY', help_text="Caretaker role slot ('PRIMARY' or 'SECONDARY').", max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', help_text='Approval status of this link.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('senior', models.ForeignKey(help_text='The linked senior.', on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to='voice.seniorprofile')),
            ],
            options={
                'verbose_name': 'Caregiver Elder Link',
                'verbose_name_plural': 'Caregiver Elder Links',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('senior', 'caretaker_phone'), name='unique_senior_caretaker_phone')],
            },
        ),
    ]
